apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadnmin9371-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadnmin9371-tenant-component
    app.kubernetes.io/part-of: loadnmin9371-tenant-app
  name: loadnmin9371-tenant-component
  namespace: loadnmin9371-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: loadnmin9371-tenant-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: loadnmin9371-tenant-component
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images:653a419d462942d4bde4cdc6a2396bd1
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
