apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadnmin9371-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadnmin9371-tenant-component
    app.kubernetes.io/part-of: loadnmin9371-tenant-app
  name: loadnmin9371-tenant-component
  namespace: loadnmin9371-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadnmin9371-tenant-component
    weight: null
status: {}
